version: '3'
services:
  backend:
    build: backend
    ports:
      - "3000:3000"
    env_file:
      - ./backend/.env
    networks:
      - network-icasei

  frontend-mf_drawler:
    build: frontend-mf_drawler
    networks:
      - network-icasei

  frontend-mf_videos:
    build: frontend-mf_videos
    networks:
      - network-icasei

  nginx:
    build: nginx
    ports:
      - "80:80"
    networks:
      - network-icasei

networks:
  network-icasei:
    driver: bridge
